spring:
  application:
    name: demo-consumer # Spring 应用名
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
    loadbalancer:
      # Spring Cloud Loadbalancer 重启配置，对应 LoadBalancerRetryProperties 配置类
      retry:
        enabled: true # 是否开启重启，默认为 false 关闭重试。

server:
  port: 28080 # 服务器端口。默认为 8080

ribbon:
  ConnectTimeout: 1
  ReadTimeout: 1
  restclient:
    enabled: true

demo-provider:
  ribbon:
    ConnectTimeout: 1
    ReadTimeout: 1
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 1
    MaxAutoRetries: 1
